# Generated by Django 3.2.25 on 2025-12-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_unit_of_measure'),
        ('accounts', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_warehouses',
            field=models.ManyToManyField(blank=True, related_name='users', to='products.Warehouse'),
        ),
    ]
