# Generated by Django 3.2.25 on 2025-11-25 12:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20251122_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_locations', to='products.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BinStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_stock_items', to='products.binlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_stock_items', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_stock_items', to='products.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='binstockitem',
            index=models.Index(fields=['product', 'warehouse', 'bin'], name='products_bi_product_3c35cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='binstockitem',
            unique_together={('product', 'warehouse', 'bin')},
        ),
        migrations.AlterUniqueTogether(
            name='binlocation',
            unique_together={('warehouse', 'code')},
        ),
    ]
