# Generated by Django 3.2.25 on 2025-11-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20251125_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_bin',
            field=models.ForeignKey(blank=True, help_text='Preferred put-away bin for this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='products.binlocation'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_quarantine',
            field=models.BooleanField(default=False, help_text='If enabled, customer returns can be routed into this warehouse instead of the original shipping warehouse.'),
        ),
    ]
