# Generated by Django 3.2.25 on 2025-11-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_unitconversion_unitofmeasure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitConversion',
        ),
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
    ]
