# Generated by Django 3.2.25 on 2025-11-26 10:37

from django.db import migrations, models
import django.db.models.deletion


def create_default_unit_of_measure(apps, schema_editor):
    """Create a default unit of measure for existing products"""
    UnitOfMeasure = apps.get_model('products', 'UnitOfMeasure')
    if not UnitOfMeasure.objects.exists():
        UnitOfMeasure.objects.create(
            name='Pieces',
            code='PCS',
            description='Default unit for counting individual items',
            is_active=True
        )


def set_default_stock_unit(apps, schema_editor):
    """Set default stock unit for existing products"""
    Product = apps.get_model('products', 'Product')
    UnitOfMeasure = apps.get_model('products', 'UnitOfMeasure')
    
    # Get or create the default unit
    try:
        default_unit = UnitOfMeasure.objects.get(code='PCS')
    except UnitOfMeasure.DoesNotExist:
        default_unit = UnitOfMeasure.objects.create(
            name='Pieces',
            code='PCS',
            description='Default unit for counting individual items',
            is_active=True
        )
    
    # Update all existing products to use the default unit
    Product.objects.filter(stock_unit__isnull=True).update(stock_unit=default_unit)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20251126_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text="How many 'to_unit' units equal one 'from_unit' unit", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='products.unitofmeasure')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='products.unitofmeasure')),
            ],
            options={
                'ordering': ['from_unit__name'],
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
        # Create default unit of measure
        migrations.RunPython(create_default_unit_of_measure, reverse_code=migrations.RunPython.noop),
        # Add fields with null=True temporarily
        migrations.AddField(
            model_name='product',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, help_text='Unit typically used when purchasing this product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_products', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.ForeignKey(help_text='Canonical unit for stock accounting', on_delete=django.db.models.deletion.PROTECT, related_name='stock_products', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='How many stock_units equal one purchase_unit (if applicable)', max_digits=10),
        ),
        # Set default stock unit for existing products
        migrations.RunPython(set_default_stock_unit, reverse_code=migrations.RunPython.noop),
    ]