# Generated by Django 3.2.25 on 2025-11-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_unit_of_measure_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measure',
        ),
    ]
