# Generated by Django 3.2.25 on 2025-11-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20251126_1028'),
        ('operations', '0003_auto_20251125_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Optional bin from which stock is picked', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.binlocation'),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Optional bin where stock is put away', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.binlocation'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.binlocation'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Destination bin in the target warehouse (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.binlocation'),
        ),
    ]
