# Generated by Django 3.2.25 on 2025-11-26 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20251126_1028'),
        ('operations', '0004_auto_20251126_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('picking', 'Picking'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_waves', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pick_waves', to=settings.AUTH_USER_MODEL)),
                ('delivery_orders', models.ManyToManyField(blank=True, related_name='pick_waves', to='operations.DeliveryOrder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_waves', to='products.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
