# Generated by Django 3.2.25 on 2025-11-26 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0006_auto_20251126_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery Order'), ('return', 'Return Order'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment'), ('cycle_count', 'Cycle Count Task'), ('pick_wave', 'Pick Wave')], max_length=20)),
                ('document_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery Order'), ('return', 'Return Order'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment'), ('cycle_count', 'Cycle Count Task'), ('pick_wave', 'Pick Wave')], max_length=20)),
                ('document_id', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['document_type', 'document_id', 'created_at'], name='operations__documen_c4ce38_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document_type', 'document_id'], name='operations__documen_9e145f_idx'),
        ),
    ]
