# Generated by Django 3.2.25 on 2025-11-26 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0007_auto_20251126_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('products', 'Products'), ('receipts', 'Receipts'), ('deliveries', 'Deliveries'), ('returns', 'Returns'), ('transfers', 'Transfers'), ('adjustments', 'Adjustments'), ('cycle_counts', 'Cycle Counts'), ('pick_waves', 'Pick Waves'), ('ledger', 'Stock Ledger')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(help_text='Serialized filter parameters')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default view for this page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'page_key', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='savedview',
            index=models.Index(fields=['user', 'page_key'], name='operations__user_id_72c72e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedview',
            unique_together={('user', 'page_key', 'name')},
        ),
    ]
