# Generated by Django 3.2.25 on 2025-11-26 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0008_auto_20251126_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('validate', 'Validate'), ('cancel', 'Cancel')], max_length=20)),
                ('model', models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery Order'), ('return', 'Return Order'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment'), ('cycle_count', 'Cycle Count Task'), ('pick_wave', 'Pick Wave'), ('product', 'Product'), ('warehouse', 'Warehouse'), ('supplier', 'Supplier'), ('user', 'User'), ('bin_location', 'Bin Location')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=200)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='operations__user_id_88bf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model', 'object_id'], name='operations__model_f54978_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='operations__action_5ceaa5_idx'),
        ),
    ]
