# Generated by Django 3.2.25 on 2025-11-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20251126_1230'),
    ]

    operations = [
    ]
