# Generated by Django 3.2.25 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_transferitem_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='operations__document_f27f45_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='operations__action_1b6548_idx',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['document_type', 'document_id'], name='operations__documen_990b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='operations__action_9ee569_idx'),
        ),
    ]
