# Generated by Django 3.2.25 on 2025-12-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_unit_of_measure'),
        ('operations', '0015_auto_20251129_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='document_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery Order'), ('return', 'Return Order'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment'), ('deliveryorder', 'Delivery Order (legacy)'), ('returnorder', 'Return Order (legacy)'), ('internaltransfer', 'Internal Transfer (legacy)'), ('stockadjustment', 'Stock Adjustment (legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('validation', 'Validation'), ('status_change', 'Status Change'), ('approval', 'Approval'), ('update', 'Update'), ('comment', 'Comment'), ('access_change', 'Access Change')], max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery Order'), ('return', 'Return Order'), ('transfer', 'Internal Transfer'), ('adjustment', 'Stock Adjustment'), ('cycle_count', 'Cycle Count')], max_length=20)),
                ('threshold_total_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse')),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
            },
        ),
    ]
