# Generated by Django 3.2.25 on 2025-11-29 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='event_types',
            field=models.JSONField(default=list, help_text='Subset of event types this webhook should receive. Empty list = all events.'),
        ),
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='secret',
            field=models.CharField(help_text='Secret used to sign webhook requests (HMAC-SHA256)', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='url',
            field=models.URLField(help_text='Endpoint URL to send webhook payloads to'),
        ),
    ]
